package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Agencia generated by hbm2java
 */
public class Agencia implements java.io.Serializable {

    private int id;
    private int iddistrito;
    private String razonsocial;
    private String nombrecomercial;
    private long ruc;
    private long telefono;
    private String urllogo;
    private String direccion;

    private int limit;
    private Date datelimit;

    private int idtipo;
    private boolean estado;

    public Agencia() {
    }

    public Agencia(int id, int iddistrito, String razonsocial, String nombrecomercial, long ruc, long telefono, String urllogo, String direccion) {
        this.id = id;
        this.iddistrito = iddistrito;
        this.razonsocial = razonsocial;
        this.nombrecomercial = nombrecomercial;
        this.ruc = ruc;
        this.telefono = telefono;
        this.urllogo = urllogo;
        this.direccion = direccion;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIddistrito() {
        return this.iddistrito;
    }

    public void setIddistrito(int iddistrito) {
        this.iddistrito = iddistrito;
    }

    public String getRazonsocial() {
        return this.razonsocial;
    }

    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }

    public String getNombrecomercial() {
        return nombrecomercial;
    }

    public void setNombrecomercial(String nombrecomercial) {
        this.nombrecomercial = nombrecomercial;
    }

    public long getRuc() {
        return this.ruc;
    }

    public void setRuc(long ruc) {
        this.ruc = ruc;
    }

    public long getTelefono() {
        return this.telefono;
    }

    public void setTelefono(long telefono) {
        this.telefono = telefono;
    }

    public String getUrllogo() {
        return this.urllogo;
    }

    public void setUrllogo(String urllogo) {
        this.urllogo = urllogo;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public int getLimit() {
        return limit;
    }

    public void setLimit(int limit) {
        this.limit = limit;
    }

    public Date getDatelimit() {
        return datelimit;
    }

    public void setDatelimit(Date datelimit) {
        this.datelimit = datelimit;
    }

    public int getIdtipo() {
        return idtipo;
    }

    public void setIdtipo(int idtipo) {
        this.idtipo = idtipo;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    
    @Override
    public String toString(){
        return nombrecomercial;
    }

}
