package com.besoft.siadi.entity;
// Generated 03/06/2017 09:12:02 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Asistencia generated by hbm2java
 */
public class Asistencia implements java.io.Serializable {

    private int id;
    private Contrato contrato;
    private int idturno;
    private int idttipoasistencia;
    private int tardanza;
    private Date fecha;
    private Date horaentrada;
    private Date horasalida;
    private Date rhoraentrada;
    private Date rhorasalida;

    public Asistencia() {
    }

    public Asistencia(int id, Contrato contrato, Date fecha, Date horaentrada, Date horasalida, Date rhoraentrada) {
        this.id = id;
        this.contrato = contrato;
        this.fecha = fecha;
        this.horaentrada = horaentrada;
        this.horasalida = horasalida;
        this.rhoraentrada = rhoraentrada;
    }

    public Asistencia(int id, Contrato contrato, int idturno, int idttipoasistencia, int tardanza, Date fecha, Date horaentrada, Date horasalida, Date rhoraentrada, Date rhorasalida) {
        this.id = id;
        this.contrato = contrato;
        this.idturno = idturno;
        this.idttipoasistencia = idttipoasistencia;
        this.tardanza = tardanza;
        this.fecha = fecha;
        this.horaentrada = horaentrada;
        this.horasalida = horasalida;
        this.rhoraentrada = rhoraentrada;
        this.rhorasalida = rhorasalida;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Contrato getContrato() {
        return contrato;
    }

    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    public int getIdturno() {
        return idturno;
    }

    public void setIdturno(int idturno) {
        this.idturno = idturno;
    }

    public int getIdttipoasistencia() {
        return idttipoasistencia;
    }

    public void setIdttipoasistencia(int idttipoasistencia) {
        this.idttipoasistencia = idttipoasistencia;
    }

    public int getTardanza() {
        return tardanza;
    }

    public void setTardanza(int tardanza) {
        this.tardanza = tardanza;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Date getHoraentrada() {
        return horaentrada;
    }

    public void setHoraentrada(Date horaentrada) {
        this.horaentrada = horaentrada;
    }

    public Date getHorasalida() {
        return horasalida;
    }

    public void setHorasalida(Date horasalida) {
        this.horasalida = horasalida;
    }

    public Date getRhoraentrada() {
        return rhoraentrada;
    }

    public void setRhoraentrada(Date rhoraentrada) {
        this.rhoraentrada = rhoraentrada;
    }

    public Date getRhorasalida() {
        return rhorasalida;
    }

    public void setRhorasalida(Date rhorasalida) {
        this.rhorasalida = rhorasalida;
    }

}
