package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Bobeda generated by hbm2java
 */
public class Bobeda implements java.io.Serializable {

    private int id;
    private Agencia agencia;
    private String nombre;
    private double montoapertura;
    private double montocierre;
    private Date fechaapertura;
    private Date fechacierre;
    private boolean estado;
    private int diezc;
    private int veintec;
    private int cincuentac;
    private int uns;
    private int doss;
    private int cincos;
    private int diezs;
    private int veintes;
    private int cincuentas;
    private int ciens;
    private int doscientoss;
    private int diezcz;
    private int veintecz;
    private int cincuentacz;
    private int unsz;
    private int dossz;
    private int cincosz;
    private int diezsz;
    private int veintesz;
    private int cincuentasz;
    private int ciensz;
    private int doscientossz;
    private int idusuariocrea;
    private Date fechusuariocrea;
    private Integer idusuariomod;
    private Date fechusuariomod;

    public Bobeda() {
    }

    public Bobeda(int id, Agencia agencia, String nombre, double montoapertura, double montocierre, Date fechaapertura, boolean estado, int diezc, int veintec, int cincuentac, int uns, int doss, int cincos, int diezs, int veintes, int cincuentas, int ciens, int doscientoss, int diezcz, int veintecz, int cincuentacz, int unsz, int dossz, int cincosz, int diezsz, int veintesz, int cincuentasz, int ciensz, int doscientossz, int idusuariocrea, Date fechusuariocrea) {
        this.id = id;
        this.agencia = agencia;
        this.nombre = nombre;
        this.montoapertura = montoapertura;
        this.montocierre = montocierre;
        this.fechaapertura = fechaapertura;
        this.estado = estado;
        this.diezc = diezc;
        this.veintec = veintec;
        this.cincuentac = cincuentac;
        this.uns = uns;
        this.doss = doss;
        this.cincos = cincos;
        this.diezs = diezs;
        this.veintes = veintes;
        this.cincuentas = cincuentas;
        this.ciens = ciens;
        this.doscientoss = doscientoss;
        this.diezcz = diezcz;
        this.veintecz = veintecz;
        this.cincuentacz = cincuentacz;
        this.unsz = unsz;
        this.dossz = dossz;
        this.cincosz = cincosz;
        this.diezsz = diezsz;
        this.veintesz = veintesz;
        this.cincuentasz = cincuentasz;
        this.ciensz = ciensz;
        this.doscientossz = doscientossz;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
    }

    public Bobeda(int id, Agencia agencia, String nombre, double montoapertura, double montocierre, Date fechaapertura, Date fechacierre, boolean estado, int diezc, int veintec, int cincuentac, int uns, int doss, int cincos, int diezs, int veintes, int cincuentas, int ciens, int doscientoss, int diezcz, int veintecz, int cincuentacz, int unsz, int dossz, int cincosz, int diezsz, int veintesz, int cincuentasz, int ciensz, int doscientossz, int idusuariocrea, Date fechusuariocrea, Integer idusuariomod, Date fechusuariomod) {
        this.id = id;
        this.agencia = agencia;
        this.nombre = nombre;
        this.montoapertura = montoapertura;
        this.montocierre = montocierre;
        this.fechaapertura = fechaapertura;
        this.fechacierre = fechacierre;
        this.estado = estado;
        this.diezc = diezc;
        this.veintec = veintec;
        this.cincuentac = cincuentac;
        this.uns = uns;
        this.doss = doss;
        this.cincos = cincos;
        this.diezs = diezs;
        this.veintes = veintes;
        this.cincuentas = cincuentas;
        this.ciens = ciens;
        this.doscientoss = doscientoss;
        this.diezcz = diezcz;
        this.veintecz = veintecz;
        this.cincuentacz = cincuentacz;
        this.unsz = unsz;
        this.dossz = dossz;
        this.cincosz = cincosz;
        this.diezsz = diezsz;
        this.veintesz = veintesz;
        this.cincuentasz = cincuentasz;
        this.ciensz = ciensz;
        this.doscientossz = doscientossz;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
        this.idusuariomod = idusuariomod;
        this.fechusuariomod = fechusuariomod;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Agencia getAgencia() {
        return this.agencia;
    }

    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public double getMontoapertura() {
        return this.montoapertura;
    }

    public void setMontoapertura(double montoapertura) {
        this.montoapertura = montoapertura;
    }

    public double getMontocierre() {
        return this.montocierre;
    }

    public void setMontocierre(double montocierre) {
        this.montocierre = montocierre;
    }

    public Date getFechaapertura() {
        return this.fechaapertura;
    }

    public void setFechaapertura(Date fechaapertura) {
        this.fechaapertura = fechaapertura;
    }

    public Date getFechacierre() {
        return this.fechacierre;
    }

    public void setFechacierre(Date fechacierre) {
        this.fechacierre = fechacierre;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public int getDiezc() {
        return this.diezc;
    }

    public void setDiezc(int diezc) {
        this.diezc = diezc;
    }

    public int getVeintec() {
        return this.veintec;
    }

    public void setVeintec(int veintec) {
        this.veintec = veintec;
    }

    public int getCincuentac() {
        return this.cincuentac;
    }

    public void setCincuentac(int cincuentac) {
        this.cincuentac = cincuentac;
    }

    public int getUns() {
        return this.uns;
    }

    public void setUns(int uns) {
        this.uns = uns;
    }

    public int getDoss() {
        return this.doss;
    }

    public void setDoss(int doss) {
        this.doss = doss;
    }

    public int getCincos() {
        return this.cincos;
    }

    public void setCincos(int cincos) {
        this.cincos = cincos;
    }

    public int getDiezs() {
        return this.diezs;
    }

    public void setDiezs(int diezs) {
        this.diezs = diezs;
    }

    public int getVeintes() {
        return this.veintes;
    }

    public void setVeintes(int veintes) {
        this.veintes = veintes;
    }

    public int getCincuentas() {
        return this.cincuentas;
    }

    public void setCincuentas(int cincuentas) {
        this.cincuentas = cincuentas;
    }

    public int getCiens() {
        return this.ciens;
    }

    public void setCiens(int ciens) {
        this.ciens = ciens;
    }

    public int getDoscientoss() {
        return this.doscientoss;
    }

    public void setDoscientoss(int doscientoss) {
        this.doscientoss = doscientoss;
    }

    public int getDiezcz() {
        return this.diezcz;
    }

    public void setDiezcz(int diezcz) {
        this.diezcz = diezcz;
    }

    public int getVeintecz() {
        return this.veintecz;
    }

    public void setVeintecz(int veintecz) {
        this.veintecz = veintecz;
    }

    public int getCincuentacz() {
        return this.cincuentacz;
    }

    public void setCincuentacz(int cincuentacz) {
        this.cincuentacz = cincuentacz;
    }

    public int getUnsz() {
        return this.unsz;
    }

    public void setUnsz(int unsz) {
        this.unsz = unsz;
    }

    public int getDossz() {
        return this.dossz;
    }

    public void setDossz(int dossz) {
        this.dossz = dossz;
    }

    public int getCincosz() {
        return this.cincosz;
    }

    public void setCincosz(int cincosz) {
        this.cincosz = cincosz;
    }

    public int getDiezsz() {
        return this.diezsz;
    }

    public void setDiezsz(int diezsz) {
        this.diezsz = diezsz;
    }

    public int getVeintesz() {
        return this.veintesz;
    }

    public void setVeintesz(int veintesz) {
        this.veintesz = veintesz;
    }

    public int getCincuentasz() {
        return this.cincuentasz;
    }

    public void setCincuentasz(int cincuentasz) {
        this.cincuentasz = cincuentasz;
    }

    public int getCiensz() {
        return this.ciensz;
    }

    public void setCiensz(int ciensz) {
        this.ciensz = ciensz;
    }

    public int getDoscientossz() {
        return this.doscientossz;
    }

    public void setDoscientossz(int doscientossz) {
        this.doscientossz = doscientossz;
    }

    public int getIdusuariocrea() {
        return this.idusuariocrea;
    }

    public void setIdusuariocrea(int idusuariocrea) {
        this.idusuariocrea = idusuariocrea;
    }

    public Date getFechusuariocrea() {
        return this.fechusuariocrea;
    }

    public void setFechusuariocrea(Date fechusuariocrea) {
        this.fechusuariocrea = fechusuariocrea;
    }

    public Integer getIdusuariomod() {
        return this.idusuariomod;
    }

    public void setIdusuariomod(Integer idusuariomod) {
        this.idusuariomod = idusuariomod;
    }

    public Date getFechusuariomod() {
        return this.fechusuariomod;
    }

    public void setFechusuariomod(Date fechusuariomod) {
        this.fechusuariomod = fechusuariomod;
    }

}
