package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Cajero generated by hbm2java
 */
public class Cajero implements java.io.Serializable {

    private int id;
    private Caja caja;
    private int idusuario;
    private double saldoapertura;
    private double saldocierre;
    private Date fechaapertura;
    private Date fechacierre;
    private boolean estado;
    private boolean pendiente;
    private Integer diezc;
    private Integer veintec;
    private Integer cincuentac;
    private Integer uns;
    private Integer doss;
    private Integer cincos;
    private Integer diezs;
    private Integer veintes;
    private Integer cincuentas;
    private Integer ciens;
    private Integer doscientoss;
    private int idusuariocrea;
    private Date fechusuariocrea;
    private Integer idusuariomod;
    private Date fechusuariomod;

    private String nombres;

    public Cajero() {
    }

    public Cajero(int id, Caja caja, int idusuario, double saldoapertura, double saldocierre, Date fechaapertura, boolean estado, boolean pendiente, int idusuariocrea, Date fechusuariocrea) {
        this.id = id;
        this.caja = caja;
        this.idusuario = idusuario;
        this.saldoapertura = saldoapertura;
        this.saldocierre = saldocierre;
        this.fechaapertura = fechaapertura;
        this.estado = estado;
        this.pendiente = pendiente;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
    }

    public Cajero(int id, Caja caja, int idusuario, double saldoapertura, double saldocierre, Date fechaapertura, Date fechacierre, boolean estado, boolean pendiente, Integer diezc, Integer veintec, Integer cincuentac, Integer uns, Integer doss, Integer cincos, Integer diezs, Integer veintes, Integer cincuentas, Integer ciens, Integer doscientoss, int idusuariocrea, Date fechusuariocrea, Integer idusuariomod, Date fechusuariomod) {
        this.id = id;
        this.caja = caja;
        this.idusuario = idusuario;
        this.saldoapertura = saldoapertura;
        this.saldocierre = saldocierre;
        this.fechaapertura = fechaapertura;
        this.fechacierre = fechacierre;
        this.estado = estado;
        this.pendiente = pendiente;
        this.diezc = diezc;
        this.veintec = veintec;
        this.cincuentac = cincuentac;
        this.uns = uns;
        this.doss = doss;
        this.cincos = cincos;
        this.diezs = diezs;
        this.veintes = veintes;
        this.cincuentas = cincuentas;
        this.ciens = ciens;
        this.doscientoss = doscientoss;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
        this.idusuariomod = idusuariomod;
        this.fechusuariomod = fechusuariomod;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Caja getCaja() {
        return this.caja;
    }

    public void setCaja(Caja caja) {
        this.caja = caja;
    }

    public int getIdusuario() {
        return this.idusuario;
    }

    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }

    public double getSaldoapertura() {
        return this.saldoapertura;
    }

    public void setSaldoapertura(double saldoapertura) {
        this.saldoapertura = saldoapertura;
    }

    public double getSaldocierre() {
        return this.saldocierre;
    }

    public void setSaldocierre(double saldocierre) {
        this.saldocierre = saldocierre;
    }

    public Date getFechaapertura() {
        return this.fechaapertura;
    }

    public void setFechaapertura(Date fechaapertura) {
        this.fechaapertura = fechaapertura;
    }

    public Date getFechacierre() {
        return this.fechacierre;
    }

    public void setFechacierre(Date fechacierre) {
        this.fechacierre = fechacierre;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public boolean isPendiente() {
        return pendiente;
    }

    public void setPendiente(boolean pendiente) {
        this.pendiente = pendiente;
    }

    public Integer getDiezc() {
        return this.diezc;
    }

    public void setDiezc(Integer diezc) {
        this.diezc = diezc;
    }

    public Integer getVeintec() {
        return this.veintec;
    }

    public void setVeintec(Integer veintec) {
        this.veintec = veintec;
    }

    public Integer getCincuentac() {
        return this.cincuentac;
    }

    public void setCincuentac(Integer cincuentac) {
        this.cincuentac = cincuentac;
    }

    public Integer getUns() {
        return this.uns;
    }

    public void setUns(Integer uns) {
        this.uns = uns;
    }

    public Integer getDoss() {
        return this.doss;
    }

    public void setDoss(Integer doss) {
        this.doss = doss;
    }

    public Integer getCincos() {
        return this.cincos;
    }

    public void setCincos(Integer cincos) {
        this.cincos = cincos;
    }

    public Integer getDiezs() {
        return this.diezs;
    }

    public void setDiezs(Integer diezs) {
        this.diezs = diezs;
    }

    public Integer getVeintes() {
        return this.veintes;
    }

    public void setVeintes(Integer veintes) {
        this.veintes = veintes;
    }

    public Integer getCincuentas() {
        return this.cincuentas;
    }

    public void setCincuentas(Integer cincuentas) {
        this.cincuentas = cincuentas;
    }

    public Integer getCiens() {
        return this.ciens;
    }

    public void setCiens(Integer ciens) {
        this.ciens = ciens;
    }

    public Integer getDoscientoss() {
        return this.doscientoss;
    }

    public void setDoscientoss(Integer doscientoss) {
        this.doscientoss = doscientoss;
    }

    public int getIdusuariocrea() {
        return this.idusuariocrea;
    }

    public void setIdusuariocrea(int idusuariocrea) {
        this.idusuariocrea = idusuariocrea;
    }

    public Date getFechusuariocrea() {
        return this.fechusuariocrea;
    }

    public void setFechusuariocrea(Date fechusuariocrea) {
        this.fechusuariocrea = fechusuariocrea;
    }

    public Integer getIdusuariomod() {
        return this.idusuariomod;
    }

    public void setIdusuariomod(Integer idusuariomod) {
        this.idusuariomod = idusuariomod;
    }

    public Date getFechusuariomod() {
        return this.fechusuariomod;
    }

    public void setFechusuariomod(Date fechusuariomod) {
        this.fechusuariomod = fechusuariomod;
    }

    public String getNombres() {
        return nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

}
