package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Clientenatural generated by hbm2java
 */
public class Clientenatural implements java.io.Serializable {

    private int id;
    private int iddistrito;
    private int idtestadocivil;
    private int idtgenero;
    private int dni;
    private String nombre;
    private String apellidopat;
    private String apellidomat;
    private long celular;
    private String direccion;
    private String email;
    private Long ruc;
    private Date fechanac;

    public Clientenatural() {
    }

    public Clientenatural(int id, int iddistrito, int idtestadocivil, int idtgenero, int dni, String nombre, String apellidopat, String apellidomat, long celular, String direccion) {
        this.id = id;
        this.iddistrito = iddistrito;
        this.idtestadocivil = idtestadocivil;
        this.idtgenero = idtgenero;
        this.dni = dni;
        this.nombre = nombre;
        this.apellidopat = apellidopat;
        this.apellidomat = apellidomat;
        this.celular = celular;
        this.direccion = direccion;
    }

    public Clientenatural(int id, int iddistrito, int idtestadocivil, int idtgenero, int dni, String nombre, String apellidopat, String apellidomat, long celular, String direccion, String email, Long ruc, Date fechanac) {
        this.id = id;
        this.iddistrito = iddistrito;
        this.idtestadocivil = idtestadocivil;
        this.idtgenero = idtgenero;
        this.dni = dni;
        this.nombre = nombre;
        this.apellidopat = apellidopat;
        this.apellidomat = apellidomat;
        this.celular = celular;
        this.direccion = direccion;
        this.email = email;
        this.ruc = ruc;
        this.fechanac = fechanac;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIddistrito() {
        return this.iddistrito;
    }

    public void setIddistrito(int iddistrito) {
        this.iddistrito = iddistrito;
    }

    public int getIdtestadocivil() {
        return this.idtestadocivil;
    }

    public void setIdtestadocivil(int idtestadocivil) {
        this.idtestadocivil = idtestadocivil;
    }

    public int getIdtgenero() {
        return this.idtgenero;
    }

    public void setIdtgenero(int idtgenero) {
        this.idtgenero = idtgenero;
    }

    public int getDni() {
        return this.dni;
    }

    public void setDni(int dni) {
        this.dni = dni;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidopat() {
        return this.apellidopat;
    }

    public void setApellidopat(String apellidopat) {
        this.apellidopat = apellidopat;
    }

    public String getApellidomat() {
        return this.apellidomat;
    }

    public void setApellidomat(String apellidomat) {
        this.apellidomat = apellidomat;
    }

    public long getCelular() {
        return this.celular;
    }

    public void setCelular(long celular) {
        this.celular = celular;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Long getRuc() {
        return this.ruc;
    }

    public void setRuc(Long ruc) {
        this.ruc = ruc;
    }

    public Date getFechanac() {
        return this.fechanac;
    }

    public void setFechanac(Date fechanac) {
        this.fechanac = fechanac;
    }

}
