package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Agencia generated by hbm2java
 */
public class Comprobante implements java.io.Serializable {

    private int id;
    private Agencia agencia;
    private int idttipocomprobante;
    private String nombre;
    private String abreviatura;
    private int numero;
    private int serie;
    private int longnumero;
    private int longserie;
    private boolean estado;
    private int idusuariocrea;
    private Date fechusuariocrea;
    private Integer idusuariomod;
    private Date fechusuariomod;

    public Comprobante() {
    }

    public Comprobante(int id, Agencia agencia, int idttipocomprobante, String nombre, String abreviatura, int numero, int serie, int longnumero, int longserie, boolean estado, int idusuariocrea, Date fechusuariocrea) {
        this.id = id;
        this.agencia = agencia;
        this.idttipocomprobante = idttipocomprobante;
        this.nombre = nombre;
        this.abreviatura = abreviatura;
        this.numero = numero;
        this.serie = serie;
        this.longnumero = longnumero;
        this.longserie = longserie;
        this.estado = estado;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
    }

    public Comprobante(int id, Agencia agencia, int idttipocomprobante, String nombre, String abreviatura, int numero, int serie, int longnumero, int longserie, boolean estado, int idusuariocrea, Date fechusuariocrea, Integer idusuariomod, Date fechusuariomod) {
        this.id = id;
        this.agencia = agencia;
        this.idttipocomprobante = idttipocomprobante;
        this.nombre = nombre;
        this.abreviatura = abreviatura;
        this.numero = numero;
        this.serie = serie;
        this.longnumero = longnumero;
        this.longserie = longserie;
        this.estado = estado;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
        this.idusuariomod = idusuariomod;
        this.fechusuariomod = fechusuariomod;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Agencia getAgencia() {
        return agencia;
    }

    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }

    public int getIdttipocomprobante() {
        return idttipocomprobante;
    }

    public void setIdttipocomprobante(int idttipocomprobante) {
        this.idttipocomprobante = idttipocomprobante;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getAbreviatura() {
        return abreviatura;
    }

    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }

    public int getNumero() {
        return numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    public int getSerie() {
        return serie;
    }

    public void setSerie(int serie) {
        this.serie = serie;
    }

    public int getLongnumero() {
        return longnumero;
    }

    public void setLongnumero(int longnumero) {
        this.longnumero = longnumero;
    }

    public int getLongserie() {
        return longserie;
    }

    public void setLongserie(int longserie) {
        this.longserie = longserie;
    }

    public boolean isEstado() {
        return estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public int getIdusuariocrea() {
        return idusuariocrea;
    }

    public void setIdusuariocrea(int idusuariocrea) {
        this.idusuariocrea = idusuariocrea;
    }

    public Date getFechusuariocrea() {
        return fechusuariocrea;
    }

    public void setFechusuariocrea(Date fechusuariocrea) {
        this.fechusuariocrea = fechusuariocrea;
    }

    public Integer getIdusuariomod() {
        return idusuariomod;
    }

    public void setIdusuariomod(Integer idusuariomod) {
        this.idusuariomod = idusuariomod;
    }

    public Date getFechusuariomod() {
        return fechusuariomod;
    }

    public void setFechusuariomod(Date fechusuariomod) {
        this.fechusuariomod = fechusuariomod;
    }

}
