package com.besoft.siadi.entity;
// Generated 03/06/2017 09:32:27 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Control generated by hbm2java
 */
public class Control implements java.io.Serializable {

    private int id;
    private Contrato contrato;
    private Justificacion justificacion;
    private Permiso permiso;
    private Sancion sancion;
    private Date fecha;
    private int idusuariocrea;
    private Date fechusuariocrea;
    private Integer idusuariomod;
    private Date fechusuariomod;

    public Control() {
    }

    public Control(int id, Contrato contrato, Date fecha, int idusuariocrea, Date fechusuariocrea) {
        this.id = id;
        this.contrato = contrato;
        this.fecha = fecha;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
    }

    public Control(int id, Contrato contrato, Justificacion justificacion, Permiso permiso, Sancion sancion, Date fecha, int idusuariocrea, Date fechusuariocrea, Integer idusuariomod, Date fechusuariomod) {
        this.id = id;
        this.contrato = contrato;
        this.justificacion = justificacion;
        this.permiso = permiso;
        this.sancion = sancion;
        this.fecha = fecha;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
        this.idusuariomod = idusuariomod;
        this.fechusuariomod = fechusuariomod;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Contrato getContrato() {
        return this.contrato;
    }

    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    public Justificacion getJustificacion() {
        return this.justificacion;
    }

    public void setJustificacion(Justificacion justificacion) {
        this.justificacion = justificacion;
    }

    public Permiso getPermiso() {
        return this.permiso;
    }

    public void setPermiso(Permiso permiso) {
        this.permiso = permiso;
    }

    public Sancion getSancion() {
        return this.sancion;
    }

    public void setSancion(Sancion sancion) {
        this.sancion = sancion;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public int getIdusuariocrea() {
        return this.idusuariocrea;
    }

    public void setIdusuariocrea(int idusuariocrea) {
        this.idusuariocrea = idusuariocrea;
    }

    public Date getFechusuariocrea() {
        return this.fechusuariocrea;
    }

    public void setFechusuariocrea(Date fechusuariocrea) {
        this.fechusuariocrea = fechusuariocrea;
    }

    public Integer getIdusuariomod() {
        return this.idusuariomod;
    }

    public void setIdusuariomod(Integer idusuariomod) {
        this.idusuariomod = idusuariomod;
    }

    public Date getFechusuariomod() {
        return this.fechusuariomod;
    }

    public void setFechusuariomod(Date fechusuariomod) {
        this.fechusuariomod = fechusuariomod;
    }

}
