package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

/**
 * Departamento generated by hbm2java
 */
public class Departamento implements java.io.Serializable {

    private int id;
    private Pais pais;
    private String denominacion;

    public Departamento() {
    }

    public Departamento(int id, Pais pais, String denominacion) {
        this.id = id;
        this.pais = pais;
        this.denominacion = denominacion;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Pais getPais() {
        return this.pais;
    }

    public void setPais(Pais pais) {
        this.pais = pais;
    }

    public String getDenominacion() {
        return this.denominacion;
    }

    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }
}
