package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa implements java.io.Serializable {

    private int id;
    private Producto producto;
    private Venta venta;
    private double cantidad;
    private double cantidadperfecto;
    private double cantidaddaniado;
    private double preciounitario;
    private double subtotal;

    private Inventario inventario;

    public Detalleventa() {
    }

    public Detalleventa(int id, Producto producto, Venta venta, double cantidad, double cantidadperfecto, double cantidaddaniado, double preciounitario, double subtotal) {
        this.id = id;
        this.producto = producto;
        this.venta = venta;
        this.cantidad = cantidad;
        this.cantidadperfecto = cantidadperfecto;
        this.cantidaddaniado = cantidaddaniado;
        this.preciounitario = preciounitario;
        this.subtotal = subtotal;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public Venta getVenta() {
        return this.venta;
    }

    public void setVenta(Venta venta) {
        this.venta = venta;
    }

    public double getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }

    public double getCantidadperfecto() {
        return this.cantidadperfecto;
    }

    public void setCantidadperfecto(double cantidadperfecto) {
        this.cantidadperfecto = cantidadperfecto;
    }

    public double getCantidaddaniado() {
        return this.cantidaddaniado;
    }

    public void setCantidaddaniado(double cantidaddaniado) {
        this.cantidaddaniado = cantidaddaniado;
    }

    public double getPreciounitario() {
        return this.preciounitario;
    }

    public void setPreciounitario(double preciounitario) {
        this.preciounitario = preciounitario;
    }

    public double getSubtotal() {
        return this.subtotal;
    }

    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }

    public Inventario getInventario() {
        return inventario;
    }

    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }

}
