package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

/**
 * Funcionacceso generated by hbm2java
 */
public class Funcionacceso implements java.io.Serializable {

    private int id;
    private Rolacceso rolacceso;
    private String nombre;
    private String codigo;
    private String ruta;
    private String icono;
    private boolean estado;

    public Funcionacceso() {
    }

    public Funcionacceso(int id, Rolacceso rolacceso, String nombre, String codigo, String ruta, String icono, boolean estado) {
        this.id = id;
        this.rolacceso = rolacceso;
        this.nombre = nombre;
        this.codigo = codigo;
        this.ruta = ruta;
        this.icono = icono;
        this.estado = estado;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Rolacceso getRolacceso() {
        return this.rolacceso;
    }

    public void setRolacceso(Rolacceso rolacceso) {
        this.rolacceso = rolacceso;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getRuta() {
        return this.ruta;
    }

    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    public String getIcono() {
        return this.icono;
    }

    public void setIcono(String icono) {
        this.icono = icono;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

}
