package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Inventarioiniciomes generated by hbm2java
 */
public class Inventarioiniciomes implements java.io.Serializable {

    private int id;
    private Producto producto;
    private Agencia agencia;
    private double cantidad;
    private double precio;
    private Date fecha;
    private int anio;
    private int mes;
    private int dia;

    public Inventarioiniciomes() {
    }

    public Inventarioiniciomes(Producto producto, Agencia agencia, double cantidad, double precio, Date fecha, int anio, int mes, int dia) {
        this.producto = producto;
        this.agencia = agencia;
        this.cantidad = cantidad;
        this.precio = precio;
        this.fecha = fecha;
        this.anio = anio;
        this.mes = mes;
        this.dia = dia;
    }

    public Inventarioiniciomes(int id, Producto producto, Agencia agencia, double cantidad, double precio, Date fecha, int anio, int mes, int dia) {
        this.id = id;
        this.producto = producto;
        this.agencia = agencia;
        this.cantidad = cantidad;
        this.precio = precio;
        this.fecha = fecha;
        this.anio = anio;
        this.mes = mes;
        this.dia = dia;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public Agencia getAgencia() {
        return agencia;
    }

    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }

    public double getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }

    public double getPrecio() {
        return this.precio;
    }

    public void setPrecio(double precio) {
        this.precio = precio;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public int getAnio() {
        return this.anio;
    }

    public void setAnio(int anio) {
        this.anio = anio;
    }

    public int getMes() {
        return this.mes;
    }

    public void setMes(int mes) {
        this.mes = mes;
    }

    public int getDia() {
        return this.dia;
    }

    public void setDia(int dia) {
        this.dia = dia;
    }

}
