package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Inventario generated by hbm2java
 */
public class Inventario implements java.io.Serializable {

    private int id;
    private Andamio andamio;
    private Producto producto;
    private double cantidad;
    private double preciomenmin;
    private double preciomenmax;
    private double preciomaymin;
    private double preciomaymax;
    private boolean estado;
    private int idusuariocrea;
    private Date fechusuariocrea;
    private Integer idusuariomod;
    private Date fechusuariomod;

    public Inventario() {
    }

    public Inventario(int id, Andamio andamio, Producto producto, double cantidad, double preciomenmin, double preciomenmax, double preciomaymin, double preciomaymax, boolean estado, int idusuariocrea, Date fechusuariocrea) {
        this.id = id;
        this.andamio = andamio;
        this.producto = producto;
        this.cantidad = cantidad;
        this.preciomenmin = preciomenmin;
        this.preciomenmax = preciomenmax;
        this.preciomaymin = preciomaymin;
        this.preciomaymax = preciomaymax;
        this.estado = estado;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
    }

    public Inventario(int id, Andamio andamio, Producto producto, double cantidad, double preciomenmin, double preciomenmax, double preciomaymin, double preciomaymax, boolean estado, int idusuariocrea, Date fechusuariocrea, Integer idusuariomod, Date fechusuariomod) {
        this.id = id;
        this.andamio = andamio;
        this.producto = producto;
        this.cantidad = cantidad;
        this.preciomenmin = preciomenmin;
        this.preciomenmax = preciomenmax;
        this.preciomaymin = preciomaymin;
        this.preciomaymax = preciomaymax;
        this.estado = estado;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
        this.idusuariomod = idusuariomod;
        this.fechusuariomod = fechusuariomod;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Andamio getAndamio() {
        return this.andamio;
    }

    public void setAndamio(Andamio andamio) {
        this.andamio = andamio;
    }

    public Producto getProducto() {
        return this.producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public double getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }

    public double getPreciomenmin() {
        return preciomenmin;
    }

    public void setPreciomenmin(double preciomenmin) {
        this.preciomenmin = preciomenmin;
    }

    public double getPreciomenmax() {
        return preciomenmax;
    }

    public void setPreciomenmax(double preciomenmax) {
        this.preciomenmax = preciomenmax;
    }

    public double getPreciomaymin() {
        return preciomaymin;
    }

    public void setPreciomaymin(double preciomaymin) {
        this.preciomaymin = preciomaymin;
    }

    public double getPreciomaymax() {
        return preciomaymax;
    }

    public void setPreciomaymax(double preciomaymax) {
        this.preciomaymax = preciomaymax;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public int getIdusuariocrea() {
        return this.idusuariocrea;
    }

    public void setIdusuariocrea(int idusuariocrea) {
        this.idusuariocrea = idusuariocrea;
    }

    public Date getFechusuariocrea() {
        return this.fechusuariocrea;
    }

    public void setFechusuariocrea(Date fechusuariocrea) {
        this.fechusuariocrea = fechusuariocrea;
    }

    public Integer getIdusuariomod() {
        return this.idusuariomod;
    }

    public void setIdusuariomod(Integer idusuariomod) {
        this.idusuariomod = idusuariomod;
    }

    public Date getFechusuariomod() {
        return this.fechusuariomod;
    }

    public void setFechusuariomod(Date fechusuariomod) {
        this.fechusuariomod = fechusuariomod;
    }

}
