package com.besoft.siadi.entity;
// Generated 03/06/2017 09:12:02 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Justificacion generated by hbm2java
 */
public class Justificacion implements java.io.Serializable {

    private int id;
    private int idtipojustificacion;
    private Date fechainicio;
    private Date fechafin;
    private Date horainicio;
    private Date horafin;
    private String descripcion;

    public Justificacion() {
    }

    public Justificacion(int id, int idtipojustificacion, Date fechainicio, Date fechafin, Date horainicio) {
        this.id = id;
        this.idtipojustificacion = idtipojustificacion;
        this.fechainicio = fechainicio;
        this.fechafin = fechafin;
        this.horainicio = horainicio;
    }

    public Justificacion(int id, int idtipojustificacion, Date fechainicio, Date fechafin, Date horainicio, Date horafin, String descripcion) {
        this.id = id;
        this.idtipojustificacion = idtipojustificacion;
        this.fechainicio = fechainicio;
        this.fechafin = fechafin;
        this.horainicio = horainicio;
        this.horafin = horafin;
        this.descripcion = descripcion;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIdtipojustificacion() {
        return this.idtipojustificacion;
    }

    public void setIdtipojustificacion(int idtipojustificacion) {
        this.idtipojustificacion = idtipojustificacion;
    }

    public Date getFechainicio() {
        return this.fechainicio;
    }

    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    public Date getFechafin() {
        return this.fechafin;
    }

    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }

    public Date getHorainicio() {
        return this.horainicio;
    }

    public void setHorainicio(Date horainicio) {
        this.horainicio = horainicio;
    }

    public Date getHorafin() {
        return this.horafin;
    }

    public void setHorafin(Date horafin) {
        this.horafin = horafin;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

}
