package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Movimiento generated by hbm2java
 */
public class Movimiento implements java.io.Serializable {

    private int id;
    private Agencia agencia;
    private int idtestadomovimiento;
    private int idttipomovimiento;
    private String codigo;
    private double montototal;
    private String urldocumento;
    private String observacion;
    private int idusuariocrea;
    private Date fechusuariocrea;
    private Integer idusuariomod;
    private Date fechusuariomod;

    public Movimiento() {
    }

    public Movimiento(int id, Agencia agencia, int idtestadomovimiento, int idttipomovimiento, String codigo, double montototal, int idusuariocrea, Date fechusuariocrea) {
        this.id = id;
        this.agencia = agencia;
        this.idtestadomovimiento = idtestadomovimiento;
        this.idttipomovimiento = idttipomovimiento;
        this.codigo = codigo;
        this.montototal = montototal;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
    }

    public Movimiento(int id, Agencia agencia, int idtestadomovimiento, int idttipomovimiento, String codigo, double montototal, String urldocumento, String observacion, int idusuariocrea, Date fechusuariocrea, Integer idusuariomod, Date fechusuariomod) {
        this.id = id;
        this.agencia = agencia;
        this.idtestadomovimiento = idtestadomovimiento;
        this.idttipomovimiento = idttipomovimiento;
        this.codigo = codigo;
        this.montototal = montototal;
        this.urldocumento = urldocumento;
        this.observacion = observacion;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
        this.idusuariomod = idusuariomod;
        this.fechusuariomod = fechusuariomod;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Agencia getAgencia() {
        return this.agencia;
    }

    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }

    public int getIdtestadomovimiento() {
        return this.idtestadomovimiento;
    }

    public void setIdtestadomovimiento(int idtestadomovimiento) {
        this.idtestadomovimiento = idtestadomovimiento;
    }

    public int getIdttipomovimiento() {
        return this.idttipomovimiento;
    }

    public void setIdttipomovimiento(int idttipomovimiento) {
        this.idttipomovimiento = idttipomovimiento;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public double getMontototal() {
        return this.montototal;
    }

    public void setMontototal(double montototal) {
        this.montototal = montototal;
    }

    public String getUrldocumento() {
        return this.urldocumento;
    }

    public void setUrldocumento(String urldocumento) {
        this.urldocumento = urldocumento;
    }

    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public int getIdusuariocrea() {
        return this.idusuariocrea;
    }

    public void setIdusuariocrea(int idusuariocrea) {
        this.idusuariocrea = idusuariocrea;
    }

    public Date getFechusuariocrea() {
        return this.fechusuariocrea;
    }

    public void setFechusuariocrea(Date fechusuariocrea) {
        this.fechusuariocrea = fechusuariocrea;
    }

    public Integer getIdusuariomod() {
        return this.idusuariomod;
    }

    public void setIdusuariomod(Integer idusuariomod) {
        this.idusuariomod = idusuariomod;
    }

    public Date getFechusuariomod() {
        return this.fechusuariomod;
    }

    public void setFechusuariomod(Date fechusuariomod) {
        this.fechusuariomod = fechusuariomod;
    }

}
