package com.besoft.siadi.entity;
// Generated 03/06/2017 09:12:02 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Permiso generated by hbm2java
 */
public class Permiso implements java.io.Serializable {

    private int id;
    private Contrato contrato;
    private int idttipopermiso;
    private Date fecha;
    private Date horasalida;
    private Date horaretorno;
    private int autorizja;
    private int autorizjp;
    private String destino;
    private String descripcion;

    public Permiso() {
    }

    public Permiso(int id, Contrato contrato, int idttipopermiso, Date fecha, Date horasalida, Date horaretorno, int autorizja, int autorizjp, String destino, String descripcion) {
        this.id = id;
        this.contrato = contrato;
        this.idttipopermiso = idttipopermiso;
        this.fecha = fecha;
        this.horasalida = horasalida;
        this.horaretorno = horaretorno;
        this.autorizja = autorizja;
        this.autorizjp = autorizjp;
        this.destino = destino;
        this.descripcion = descripcion;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Contrato getContrato() {
        return contrato;
    }

    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    public int getIdttipopermiso() {
        return idttipopermiso;
    }

    public void setIdttipopermiso(int idttipopermiso) {
        this.idttipopermiso = idttipopermiso;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public Date getHorasalida() {
        return horasalida;
    }

    public void setHorasalida(Date horasalida) {
        this.horasalida = horasalida;
    }

    public Date getHoraretorno() {
        return horaretorno;
    }

    public void setHoraretorno(Date horaretorno) {
        this.horaretorno = horaretorno;
    }

    public int getAutorizja() {
        return autorizja;
    }

    public void setAutorizja(int autorizja) {
        this.autorizja = autorizja;
    }

    public int getAutorizjp() {
        return autorizjp;
    }

    public void setAutorizjp(int autorizjp) {
        this.autorizjp = autorizjp;
    }

    public String getDestino() {
        return destino;
    }

    public void setDestino(String destino) {
        this.destino = destino;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

}
