package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

    private int id;
    private Categoria categoria;
    private Marca marca;
    private int idttipo;
    private int idtunidadmedida;
    private String codigo;
    private String nombre;
    private String descripcion;
    private String urlfoto;
    private int cantidadmin;
    private boolean estado;
    private int idusuariocrea;
    private Date fechusuariocrea;
    private Integer idusuariomod;
    private Date fechusuariomod;

    public Producto() {
    }

    public Producto(int id, Categoria categoria, Marca marca, int idttipo, int idtunidadmedida, String codigo, String nombre, int cantidadmin, boolean estado, int idusuariocrea, Date fechusuariocrea) {
        this.id = id;
        this.categoria = categoria;
        this.marca = marca;
        this.idttipo = idttipo;
        this.idtunidadmedida = idtunidadmedida;
        this.codigo = codigo;
        this.nombre = nombre;
        this.cantidadmin = cantidadmin;
        this.estado = estado;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
    }

    public Producto(int id, Categoria categoria, Marca marca, int idttipo, int idtunidadmedida, String codigo, String nombre, String descripcion, String urlfoto, int cantidadmin, boolean estado, int idusuariocrea, Date fechusuariocrea, Integer idusuariomod, Date fechusuariomod) {
        this.id = id;
        this.categoria = categoria;
        this.marca = marca;
        this.idttipo = idttipo;
        this.idtunidadmedida = idtunidadmedida;
        this.codigo = codigo;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.urlfoto = urlfoto;
        this.cantidadmin = cantidadmin;
        this.estado = estado;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
        this.idusuariomod = idusuariomod;
        this.fechusuariomod = fechusuariomod;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Categoria getCategoria() {
        return this.categoria;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    public Marca getMarca() {
        return this.marca;
    }

    public void setMarca(Marca marca) {
        this.marca = marca;
    }

    public int getIdttipo() {
        return this.idttipo;
    }

    public void setIdttipo(int idttipo) {
        this.idttipo = idttipo;
    }

    public int getIdtunidadmedida() {
        return this.idtunidadmedida;
    }

    public void setIdtunidadmedida(int idtunidadmedida) {
        this.idtunidadmedida = idtunidadmedida;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getUrlfoto() {
        return this.urlfoto;
    }

    public void setUrlfoto(String urlfoto) {
        this.urlfoto = urlfoto;
    }

    public int getCantidadmin() {
        return cantidadmin;
    }

    public void setCantidadmin(int cantidadmin) {
        this.cantidadmin = cantidadmin;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public int getIdusuariocrea() {
        return this.idusuariocrea;
    }

    public void setIdusuariocrea(int idusuariocrea) {
        this.idusuariocrea = idusuariocrea;
    }

    public Date getFechusuariocrea() {
        return this.fechusuariocrea;
    }

    public void setFechusuariocrea(Date fechusuariocrea) {
        this.fechusuariocrea = fechusuariocrea;
    }

    public Integer getIdusuariomod() {
        return this.idusuariomod;
    }

    public void setIdusuariomod(Integer idusuariomod) {
        this.idusuariomod = idusuariomod;
    }

    public Date getFechusuariomod() {
        return this.fechusuariomod;
    }

    public void setFechusuariomod(Date fechusuariomod) {
        this.fechusuariomod = fechusuariomod;
    }
}
