package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor implements java.io.Serializable {

    private int id;
    private Proveedorjuridico proveedorjuridico;
    private Proveedornatural proveedornatural;
    private int idttipoproveedor;
    private String codigo;
    private String observacion;
    private boolean estado;
    private int idusuariocrea;
    private Date fechusuariocrea;
    private Integer idusuariomod;
    private Date fechusuariomod;

    public Proveedor() {
    }

    public Proveedor(int id, int idttipoproveedor, String codigo, boolean estado, int idusuariocrea, Date fechusuariocrea) {
        this.id = id;
        this.idttipoproveedor = idttipoproveedor;
        this.codigo = codigo;
        this.estado = estado;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
    }

    public Proveedor(int id, Proveedorjuridico proveedorjuridico, Proveedornatural proveedornatural, int idttipoproveedor, String codigo, String observacion, boolean estado, int idusuariocrea, Date fechusuariocrea, Integer idusuariomod, Date fechusuariomod) {
        this.id = id;
        this.proveedorjuridico = proveedorjuridico;
        this.proveedornatural = proveedornatural;
        this.idttipoproveedor = idttipoproveedor;
        this.codigo = codigo;
        this.observacion = observacion;
        this.estado = estado;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
        this.idusuariomod = idusuariomod;
        this.fechusuariomod = fechusuariomod;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Proveedorjuridico getProveedorjuridico() {
        return this.proveedorjuridico;
    }

    public void setProveedorjuridico(Proveedorjuridico proveedorjuridico) {
        this.proveedorjuridico = proveedorjuridico;
    }

    public Proveedornatural getProveedornatural() {
        return this.proveedornatural;
    }

    public void setProveedornatural(Proveedornatural proveedornatural) {
        this.proveedornatural = proveedornatural;
    }

    public int getIdttipoproveedor() {
        return this.idttipoproveedor;
    }

    public void setIdttipoproveedor(int idttipoproveedor) {
        this.idttipoproveedor = idttipoproveedor;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public int getIdusuariocrea() {
        return this.idusuariocrea;
    }

    public void setIdusuariocrea(int idusuariocrea) {
        this.idusuariocrea = idusuariocrea;
    }

    public Date getFechusuariocrea() {
        return this.fechusuariocrea;
    }

    public void setFechusuariocrea(Date fechusuariocrea) {
        this.fechusuariocrea = fechusuariocrea;
    }

    public Integer getIdusuariomod() {
        return this.idusuariomod;
    }

    public void setIdusuariomod(Integer idusuariomod) {
        this.idusuariomod = idusuariomod;
    }

    public Date getFechusuariomod() {
        return this.fechusuariomod;
    }

    public void setFechusuariomod(Date fechusuariomod) {
        this.fechusuariomod = fechusuariomod;
    }

}
