package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

/**
 * Provincia generated by hbm2java
 */
public class Provincia implements java.io.Serializable {

    private int id;
    private Departamento departamento;
    private String denominacion;

    public Provincia() {
    }

    public Provincia(int id, Departamento departamento, String denominacion) {
        this.id = id;
        this.departamento = departamento;
        this.denominacion = denominacion;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Departamento getDepartamento() {
        return this.departamento;
    }

    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    public String getDenominacion() {
        return this.denominacion;
    }

    public void setDenominacion(String denominacion) {
        this.denominacion = denominacion;
    }

}
