package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.List;

/**
 * Rolacceso generated by hbm2java
 */
public class Rolacceso implements java.io.Serializable {

    private int id;
    private Moduloacceso moduloacceso;
    private String nombre;
    private String codigo;
    private String ruta;
    private String icono;
    private boolean estado;
    private List funcionaccesos;

    public Rolacceso() {
    }

    public Rolacceso(int id, Moduloacceso moduloacceso, String nombre, String codigo, String ruta, String icono, boolean estado) {
        this.id = id;
        this.moduloacceso = moduloacceso;
        this.nombre = nombre;
        this.codigo = codigo;
        this.ruta = ruta;
        this.icono = icono;
        this.estado = estado;
    }

    public Rolacceso(int id, Moduloacceso moduloacceso, String nombre, String codigo, String ruta, String icono, boolean estado, List funcionaccesos) {
        this.id = id;
        this.moduloacceso = moduloacceso;
        this.nombre = nombre;
        this.codigo = codigo;
        this.ruta = ruta;
        this.icono = icono;
        this.estado = estado;
        this.funcionaccesos = funcionaccesos;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Moduloacceso getModuloacceso() {
        return this.moduloacceso;
    }

    public void setModuloacceso(Moduloacceso moduloacceso) {
        this.moduloacceso = moduloacceso;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getRuta() {
        return this.ruta;
    }

    public void setRuta(String ruta) {
        this.ruta = ruta;
    }

    public String getIcono() {
        return this.icono;
    }

    public void setIcono(String icono) {
        this.icono = icono;
    }

    public boolean isEstado() {
        return this.estado;
    }

    public void setEstado(boolean estado) {
        this.estado = estado;
    }

    public List getFuncionaccesos() {
        return this.funcionaccesos;
    }

    public void setFuncionaccesos(List funcionaccesos) {
        this.funcionaccesos = funcionaccesos;
    }

}
