package com.besoft.siadi.entity;
// Generated 03/06/2017 09:12:02 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Sancion generated by hbm2java
 */
public class Sancion implements java.io.Serializable {

    private int id;
    private int idtiposancion;
    private Date fechainicio;
    private Date fechafin;
    private String descripcion;

    public Sancion() {
    }

    public Sancion(int id, int idtiposancion, Date fechainicio, Date fechafin) {
        this.id = id;
        this.idtiposancion = idtiposancion;
        this.fechainicio = fechainicio;
        this.fechafin = fechafin;
    }

    public Sancion(int id, int idtiposancion, Date fechainicio, Date fechafin, String descripcion) {
        this.id = id;
        this.idtiposancion = idtiposancion;
        this.fechainicio = fechainicio;
        this.fechafin = fechafin;
        this.descripcion = descripcion;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIdtiposancion() {
        return this.idtiposancion;
    }

    public void setIdtiposancion(int idtiposancion) {
        this.idtiposancion = idtiposancion;
    }

    public Date getFechainicio() {
        return this.fechainicio;
    }

    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    public Date getFechafin() {
        return this.fechafin;
    }

    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

}
