package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Transaccion generated by hbm2java
 */
public class Transaccion implements java.io.Serializable {

    private int id;
    private Cajero cajero;
    private int idttipotransaccion;
    private int idttipocomprobante;
    private double monto;
    private Date fecha;
    private String nrocomprobante;
    private String srecomprobante;
    private int idusuariocrea;
    private Date fechusuariocrea;
    private Integer idusuariomod;
    private Date fechusuariomod;

    public Transaccion() {
    }

    public Transaccion(int idttipotransaccion, int idttipocomprobante, double monto, Date fecha, int idusuariocrea, Date fechusuariocrea) {
        this.idttipotransaccion = idttipotransaccion;
        this.idttipocomprobante = idttipocomprobante;
        this.monto = monto;
        this.fecha = fecha;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
    }

    public Transaccion(int id, Cajero cajero, int idttipotransaccion, int idttipocomprobante, int monto, Date fecha, String codtransaccion, String nrocomprobante, String srecomprobante, int idusuariocrea, Date fechusuariocrea, Integer idusuariomod, Date fechusuariomod) {
        this.id = id;
        this.cajero = cajero;
        this.idttipotransaccion = idttipotransaccion;
        this.idttipocomprobante = idttipocomprobante;
        this.monto = monto;
        this.fecha = fecha;
        this.nrocomprobante = nrocomprobante;
        this.srecomprobante = srecomprobante;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
        this.idusuariomod = idusuariomod;
        this.fechusuariomod = fechusuariomod;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Cajero getCajero() {
        return this.cajero;
    }

    public void setCajero(Cajero cajero) {
        this.cajero = cajero;
    }

    public int getIdttipotransaccion() {
        return this.idttipotransaccion;
    }

    public void setIdttipotransaccion(int idttipotransaccion) {
        this.idttipotransaccion = idttipotransaccion;
    }

    public int getIdttipocomprobante() {
        return this.idttipocomprobante;
    }

    public void setIdttipocomprobante(int idttipocomprobante) {
        this.idttipocomprobante = idttipocomprobante;
    }

    public double getMonto() {
        return this.monto;
    }

    public void setMonto(double monto) {
        this.monto = monto;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getNrocomprobante() {
        return this.nrocomprobante;
    }

    public void setNrocomprobante(String nrocomprobante) {
        this.nrocomprobante = nrocomprobante;
    }

    public String getSrecomprobante() {
        return this.srecomprobante;
    }

    public void setSrecomprobante(String srecomprobante) {
        this.srecomprobante = srecomprobante;
    }

    public int getIdusuariocrea() {
        return this.idusuariocrea;
    }

    public void setIdusuariocrea(int idusuariocrea) {
        this.idusuariocrea = idusuariocrea;
    }

    public Date getFechusuariocrea() {
        return this.fechusuariocrea;
    }

    public void setFechusuariocrea(Date fechusuariocrea) {
        this.fechusuariocrea = fechusuariocrea;
    }

    public Integer getIdusuariomod() {
        return this.idusuariomod;
    }

    public void setIdusuariomod(Integer idusuariomod) {
        this.idusuariomod = idusuariomod;
    }

    public Date getFechusuariomod() {
        return this.fechusuariomod;
    }

    public void setFechusuariomod(Date fechusuariomod) {
        this.fechusuariomod = fechusuariomod;
    }

}
