package com.besoft.siadi.entity;
// Generated 03/06/2017 09:12:02 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Turno generated by hbm2java
 */
public class Turno implements java.io.Serializable {

    private int id;
    private Contrato contrato;
    private int idttipoturno;
    private Date horaentrada;
    private Date horasalida;
    private int dia;

    public Turno() {
    }

    public Turno(int id, Contrato contrato, int idttipoturno, Date horaentrada, Date horasalida, int dia) {
        this.id = id;
        this.contrato = contrato;
        this.idttipoturno = idttipoturno;
        this.horaentrada = horaentrada;
        this.horasalida = horasalida;
        this.dia = dia;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Contrato getContrato() {
        return this.contrato;
    }

    public void setContrato(Contrato contrato) {
        this.contrato = contrato;
    }

    public int getIdttipoturno() {
        return this.idttipoturno;
    }

    public void setIdttipoturno(int idttipoturno) {
        this.idttipoturno = idttipoturno;
    }

    public Date getHoraentrada() {
        return this.horaentrada;
    }

    public void setHoraentrada(Date horaentrada) {
        this.horaentrada = horaentrada;
    }

    public Date getHorasalida() {
        return this.horasalida;
    }

    public void setHorasalida(Date horasalida) {
        this.horasalida = horasalida;
    }

    public int getDia() {
        return dia;
    }

    public void setDia(int dia) {
        this.dia = dia;
    }

}
