package com.besoft.siadi.entity;
// Generated 08/10/2016 03:16:50 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Venta generated by hbm2java
 */
public class Venta implements java.io.Serializable {

    private int id;
    private Agencia agencia;
    private Cliente cliente;
    private int idttipocomprobante;
    private int idttipoventa;
    private int idtestadoventa;
    private int idcajero;
    private String codigo;
    private String nombrecliente;
    private double montototal;
    private String nrocomprobante;
    private String seriecomprobante;
    private String observacion;
    private Date fechasalida;
    private int idusuariocrea;
    private Date fechusuariocrea;
    private Integer idusuariomod;
    private Date fechusuariomod;

    public Venta() {
    }

    public Venta(int id, Agencia agencia, int idttipocomprobante, int idttipoventa, int idtestadoventa, int idcajero, String codigo, String nombrecliente, double montototal, Date fechasalida, int idusuariocrea, Date fechusuariocrea) {
        this.id = id;
        this.agencia = agencia;
        this.idttipocomprobante = idttipocomprobante;
        this.idttipoventa = idttipoventa;
        this.idtestadoventa = idtestadoventa;
        this.idcajero = idcajero;
        this.codigo = codigo;
        this.nombrecliente = nombrecliente;
        this.montototal = montototal;
        this.fechasalida = fechasalida;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
    }

    public Venta(int id, Agencia agencia, Cliente cliente, int idttipocomprobante, int idttipoventa, int idtestadoventa, int idcajero, String codigo, String nombrecliente, double montototal, String nrocomprobante, String seriecomprobante, String observacion, Date fechasalida, int idusuariocrea, Date fechusuariocrea, Integer idusuariomod, Date fechusuariomod) {
        this.id = id;
        this.agencia = agencia;
        this.cliente = cliente;
        this.idttipocomprobante = idttipocomprobante;
        this.idttipoventa = idttipoventa;
        this.idtestadoventa = idtestadoventa;
        this.idcajero = idcajero;
        this.codigo = codigo;
        this.nombrecliente = nombrecliente;
        this.montototal = montototal;
        this.nrocomprobante = nrocomprobante;
        this.seriecomprobante = seriecomprobante;
        this.observacion = observacion;
        this.fechasalida = fechasalida;
        this.idusuariocrea = idusuariocrea;
        this.fechusuariocrea = fechusuariocrea;
        this.idusuariomod = idusuariomod;
        this.fechusuariomod = fechusuariomod;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Agencia getAgencia() {
        return this.agencia;
    }

    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public int getIdttipocomprobante() {
        return this.idttipocomprobante;
    }

    public void setIdttipocomprobante(int idttipocomprobante) {
        this.idttipocomprobante = idttipocomprobante;
    }

    public int getIdttipoventa() {
        return idttipoventa;
    }

    public void setIdttipoventa(int idttipoventa) {
        this.idttipoventa = idttipoventa;
    }

    public int getIdtestadoventa() {
        return this.idtestadoventa;
    }

    public void setIdtestadoventa(int idtestadoventa) {
        this.idtestadoventa = idtestadoventa;
    }

    public int getIdcajero() {
        return idcajero;
    }

    public void setIdcajero(int idcajero) {
        this.idcajero = idcajero;
    }

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getNombrecliente() {
        return this.nombrecliente;
    }

    public void setNombrecliente(String nombrecliente) {
        this.nombrecliente = nombrecliente;
    }

    public double getMontototal() {
        return this.montototal;
    }

    public void setMontototal(double montototal) {
        this.montototal = montototal;
    }

    public String getNrocomprobante() {
        return this.nrocomprobante;
    }

    public void setNrocomprobante(String nrocomprobante) {
        this.nrocomprobante = nrocomprobante;
    }

    public String getSeriecomprobante() {
        return this.seriecomprobante;
    }

    public void setSeriecomprobante(String seriecomprobante) {
        this.seriecomprobante = seriecomprobante;
    }

    public String getObservacion() {
        return this.observacion;
    }

    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public Date getFechasalida() {
        return this.fechasalida;
    }

    public void setFechasalida(Date fechasalida) {
        this.fechasalida = fechasalida;
    }

    public int getIdusuariocrea() {
        return this.idusuariocrea;
    }

    public void setIdusuariocrea(int idusuariocrea) {
        this.idusuariocrea = idusuariocrea;
    }

    public Date getFechusuariocrea() {
        return this.fechusuariocrea;
    }

    public void setFechusuariocrea(Date fechusuariocrea) {
        this.fechusuariocrea = fechusuariocrea;
    }

    public Integer getIdusuariomod() {
        return this.idusuariomod;
    }

    public void setIdusuariomod(Integer idusuariomod) {
        this.idusuariomod = idusuariomod;
    }

    public Date getFechusuariomod() {
        return this.fechusuariomod;
    }

    public void setFechusuariomod(Date fechusuariomod) {
        this.fechusuariomod = fechusuariomod;
    }

}
